version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'yii2_message_delivery'
      MYSQL_USER: 'yii2_message_delivery'
      MYSQL_PASSWORD: 'demo'
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3310:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
  pgsql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=yii2_message_delivery
      - POSTGRES_PASSWORD=yii2_message_delivery
    ports:
      - '5510:5432'
    volumes:
      - pgsql-volume:/var/lib/postgresql/data
volumes:
  mysql-volume:
  pgsql-volume:

